services:
  db:
    image: mariadb:latest
    container_name: db
    hostname: db
    restart: always
    networks:
      - mysql-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    networks:
      - mysql-net
    container_name: phpmyadmin
    hostname: phpmyadmin
    ports:
      - 7000:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 200000K

volumes:
  db:
    name: db

networks:
  mysql-net:
    name: mysql-net